**WIP**-Create sdk-android.mdx
devrev/fern-api-docs pull request #108
Opened 2024-11-04 06:53 UTC by Atul-Butola

ISS-124016

2024-11-07 16:09 UTC, bojan requested changes
Some minor changes, but generally iOS looks pretty good!

2024-11-07 16:09 UTC, bojan commented on fern/docs/pages/plug-sdk/sdk-ios.mdx
> +The DevRev SDK offers automatic screen tracking to help you understand how users navigate through your app. Although activities are automatically tracked, you can manually track screens using the fol
We need to tweak this a bit since iOS doesn't have activities:
```suggestion
The DevRev SDK offers automatic screen tracking to help you understand how users navigate through your app. Although view controllers are automatically tracked, you can manually track screens using the following method:
```

2024-11-07 16:09 UTC, bojan commented on fern/docs/pages/plug-sdk/sdk-ios.mdx
> +To receive push notifications, you need to configure your DevRev organization by following the Push Notifications Integration guide (**TBD ITEM**).
We need Ribhu's input here for the **TBD ITEM**.

2024-11-07 16:09 UTC, bojan commented on fern/docs/pages/plug-sdk/sdk-ios.mdx
> +You need to ensure that your iOS app is configured to receive push notifications. You can follow the [Apple documentation](https://developer.apple.com/documentation/usernotifications/registering_your
Apple naming, don't ask 🤣 
```suggestion
You need to ensure that your iOS app is configured to receive push notifications. You can follow the [Apple documentation](https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns) for guidance on registering your app with Apple Push Notification Service (APNs).
```

2024-11-07 16:09 UTC, bojan commented on fern/docs/pages/plug-sdk/sdk-ios.mdx
> +The method requires a device identifier, which can either be an identifier unique to your system or the Apple-provided Vendor Identifier (IDFV). Typically, registration is called from the `AppDelegat
```suggestion
The method requires a device identifier, which can either be an identifier unique to your system or the Apple-provided Vendor Identifier (IDFV). Typically, the token registration is called from the `AppDelegate.application(_:didRegisterForRemoteNotificationsWithDeviceToken:)` method.
```

2024-11-07 17:39 UTC, bc-devrev requested changes
- Indent code samples and sub-lists under list items.
- Consolidate tab groups; don't follow a tab group for different languages with another tab group for the same languages.
- Minimize the use of tables since Turing can't interpret them.
- Address comments from EkLine; in particular never use "foo".

2024-11-07 17:39 UTC, bc-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +    android:name=".FooApplication">
Never use "foo". https://www.notion.so/devrev/What-words-or-phrases-should-be-avoided-and-why-c424af306b2f42c3b2db511e8e7dd459?pvs=4
```suggestion
    android:name=".ExampleApplication">
```

2024-11-07 17:39 UTC, bc-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +DevRev.identifyAnonymousUser("abcd1234")
Are these "examples" really necessary? They don't seem to add much over the reference.

2024-11-07 17:39 UTC, bc-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +```kotlin
Throughout, indent code samples under the numbered item.
```suggestion
   ```kotlin
```

2024-11-07 17:39 UTC, bc-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +<Tabs>
Over all there are about twice as many tab groups as necessary. Combine the code samples into the same tab as the relevant language.

2024-11-07 17:39 UTC, bc-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +| Kotlin                   | Java                                                               | Action                                                    |
This table renders poorly because the Java context is so long. Is it really necessary to repeat it in every row? Maybe put it in the header. Action should be the first column.
```suggestion
| Action | Kotlin (`DevRev`)    | Java (`DevRevObservabilityExtKt`)    |
```

2024-11-07 17:39 UTC, bc-devrev commented on fern/docs/pages/plug-sdk/sdk-ios.mdx
> +- For SwiftUI, add your credentials to `ContentView.swift`.
Indent
```suggestion
   - For SwiftUI, add your credentials to `ContentView.swift`.
```

2024-11-11 06:29 UTC, rohan-devrev requested changes
The examples for single parameter self-explanatory function signatures can be omitted.

2024-11-11 06:29 UTC, rohan-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +**NEED SYNTAX**
It shouldn't be need syntax here, this example is the syntax:
```kotlin
import ai.devrev.sdk.DevRev

class FooApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        DevRev.configure(
            context = this,
            appId = "<APP_ID>"
        )
    }
}
```

2024-11-11 06:29 UTC, rohan-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +To utilize certain features of the DevRev SDK, user identification is required. You can select from the following methods to identify users within your application:
Maybe `use` instead of `utilize`?

2024-11-11 06:29 UTC, rohan-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +DevRev.identifyAnonymousUser("abcd1234")
This can be omitted.

2024-11-11 06:29 UTC, rohan-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +You can add custom properties to the session recording to help you understand the context of the session. The properties are defined as a dictionary of string values.
Let's use `HashMap` instead of `dictionary`

2024-11-11 06:29 UTC, rohan-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +The mechanism utilizes balanced start and stop methods, both of which accept a timer name and an optional dictionary of properties.
Let's use `HashMap` instead of `dictionary`

2024-11-11 06:29 UTC, rohan-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +To balance it with a stop method, use the following:
Can we better phrase it? Balancing here isn't a very clear sentence when we are just stopping a timer.

2024-11-11 06:29 UTC, rohan-devrev commented on fern/docs/pages/plug-sdk/sdk-android.mdx
> +The DevRev backend sends push notifications to your app to alert users about new messages in the PLuG support chat.
```suggestion
DevRev sends push notifications to your app to alert users about new messages in the PLuG support chat.
```

2024-11-11 09:15 UTC, Atul-Butola commented on fern/docs/pages/plug-sdk/sdk-ios.mdx
> +The support chat feature can be displayed either as a modal screen from a specific view controller or pushed onto a navigation stack. 
@bojan Regarding "we added another method of how the support chat can be shown on screen." I have checked the Readme file and unable to find any newly added method under UIKit section, please provide the info or tag me in the Readme file.

2024-11-19 15:08 UTC, bojan requested changes
A few minor things.

2024-11-19 15:08 UTC, bojan commented on fern/docs/pages/plug-sdk/push-notification.mdx
> +    a. Go to **Settings** > **Support** > **PLuG settings** > **Mobile app notification via PLuG**.
Let's block this for a bit, we need to finalize the copy here with Ribhu. cc @rohan-devrev

2024-11-19 15:08 UTC, bojan commented on fern/docs/pages/plug-sdk/sdk-ios.mdx
There were a few minor changes in the README in devrev/ios-sdk-source#89.

2024-11-19 15:08 UTC, bojan commented on fern/docs/pages/plug-sdk/sdk-android.mdx
There were a few minor changes in the README in devrev/android-sdk-source#60 (devrev/android-sdk-source@fca2a06bc0896807280fa7c802da1c07cd18364b).

2024-11-20 08:27 UTC, bojan commented on fern/docs/pages/plug-sdk/push-notification.mdx
> +    a. Go to **Settings** > **Support** > **PLuG settings** > **Mobile app notification via PLuG**.
@Atul-Butola, @JatinRanka is raising a PR with the copy changes, he'll notify us when it's merged. cc @rohan-devrev

2024-11-25 09:52 UTC, bojan requested changes
The copies are ready.

2024-11-25 09:52 UTC, bojan commented on fern/docs/pages/plug-sdk/push-notification.mdx
> +    a. Go to **Settings** > **Support** > **PLuG settings** > **Mobile app notification via PLuG**.
```suggestion
    a. Go to **Settings** > **Support** > **PLuG settings** > **Mobile push notifications**.
```

2024-11-28 11:06 UTC, Atul-Butola commented on fern/docs/pages/plug-sdk/sdk-ios.mdx
Updated

2024-12-02 16:33 UTC, bc-devrev approved these changes
Really needs some polish but let's get it out with the few small changes I've indicated.

2024-12-02 16:33 UTC, bc-devrev commented on fern/versions/public.yml
> +          - page: Setting up push notifications in the DevRev SDK
```suggestion
          - page: Push notifications
```

2024-12-02 16:33 UTC, bc-devrev commented on fern/versions/public.yml
> +          - page: Integrate PLuG SDKs with your Android app
"Android app" is more important than "Integrate PLuG SDKs" so put it first.
```suggestion
          - page: Android app integration
```

2024-12-02 16:33 UTC, bc-devrev commented on fern/versions/public.yml
> +          - page: Integrate PLuG SDKs with your iOS app
```suggestion
          - page: iOS app integration
```

2024-12-02 16:33 UTC, bc-devrev commented
> Really needs some polish but let's get it out with the few small changes I've indicated.

And the suggestions from EkLine where appropriate.

2024-12-02 16:40 UTC, bojan commented
> > Really needs some polish but let's get it out with the few small changes I've indicated.
> 
> 
> 
> And the suggestions from EkLine where appropriate.

I noticed that most of the EkLine suggestions in the code blocks are breaking changes. I wouldn't change the code blocks since they might become incompilable.

2024-12-04 09:49 UTC, Atul-Butola commented on fern/versions/public.yml
> +          - page: Setting up push notifications in the DevRev SDK
Updated

2024-12-04 09:51 UTC, Atul-Butola commented on fern/versions/public.yml
> +          - page: Integrate PLuG SDKs with your Android app
Updated

2024-12-04 09:52 UTC, Atul-Butola commented on fern/versions/public.yml
> +          - page: Integrate PLuG SDKs with your iOS app
Updated

2024-12-04 11:18 UTC, merged