**WIP** Create sdk-react-native.mdx
devrev/fern-api-docs pull request #127
Opened 2024-12-13 09:21 UTC by Atul-Butola

no-work-item

2024-12-16 18:15 UTC, bc-devrev approved these changes
Be sure to add a link from the overview page. https://developer.devrev.ai/sdks/web/overview

2024-12-16 18:15 UTC, bc-devrev commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +1. In DevRev, go to **Settings** > **PLuG settings** copy the value under **Your unique App ID**.
I don't think this needs to be a 2-item numbered list. Just a paragraph would be ok.

2024-12-16 18:15 UTC, bc-devrev commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +To access certain features of the DevRev SDK, user identification is required.
Would it be a good idea to link to the longer user identification expalanation?

2024-12-16 18:15 UTC, bc-devrev commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +On iOS devices, you must pass the received push notification payload to the DevRev SDK for processing. The SDK will then handle the notification and execute the necessary actions.
How is this different from Android? I'm not seeing why they need to be distinguished. If it's the same method, best to cover that first then comment on iOS vs. Android rather than duplicate. And should avoid going down to H4.

2024-12-17 07:18 UTC, rohan-devrev requested changes

2024-12-17 07:18 UTC, rohan-devrev commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +The support chat feature can be shown as a modal screen from the top-most screen. 
Can we link to the PLuG support chat description here if any?

2024-12-17 07:18 UTC, rohan-devrev commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +On iOS devices, you must pass the received push notification payload to the DevRev SDK for processing. The SDK will then handle the notification and execute the necessary actions.
The examples convey the story that the handling for both platforms is different. Hence, I feel it should be better to keep these in separate sections.

2024-12-18 07:17 UTC, Atul-Butola commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +1. In DevRev, go to **Settings** > **PLuG settings** copy the value under **Your unique App ID**.
Updated

2024-12-18 07:46 UTC, Atul-Butola commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +If you haven't previously identified the user, the DevRev SDK will automatically create an anonymous user for you immediately after the SDK is configured.
Updated NOTE to mention its only for iOS

2024-12-18 07:51 UTC, Atul-Butola commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +1. In DevRev, go to **Settings** > **PLuG settings** copy the value under **Your unique App ID**.
Updated

2024-12-18 07:52 UTC, Atul-Butola commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +The support chat feature can be shown as a modal screen from the top-most screen. 
No, I have checked and we dnt have a section describing the PLuG support chat, if it needs to be added, please provide the content.

2024-12-18 07:54 UTC, Atul-Butola commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +To access certain features of the DevRev SDK, user identification is required.
If you meant linking to the "Identify your users with PLuG" section, its meant for the web SDKs and not mobile.

2024-12-18 12:43 UTC, rohan-devrev commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +The support chat feature can be shown as a modal screen from the top-most screen. 
Cool, I've checked the native integration guides as well. Looks like we can do away with it. However, can we make the description better?

Something like what we've used in the native integration:
Once user identification is complete, you can start using the chat (conversations) dialog supported by our DevRev SDK. To open the chat dialog, your application should use the `showSupport` API, as shown in the following example:

2024-12-18 14:07 UTC, rohan-devrev approved these changes

2024-12-18 14:09 UTC, Atul-Butola commented
> Be sure to add a link from the overview page. https://developer.devrev.ai/sdks/web/overview

Added

2024-12-18 14:09 UTC, Atul-Butola commented on fern/docs/pages/plug-sdk/sdk-react-native.mdx
> +The support chat feature can be shown as a modal screen from the top-most screen. 
Added

2024-12-20 05:24 UTC, merged