Add ADaaS documentation.
devrev/fern-api-docs pull request #64
Opened 2024-07-09 09:05 UTC by samod

This PR provides ADaaS public documentation for 2P/3P developers.

app.devrev.ai/devrev/works/ISS-100391

2024-07-09 20:55 UTC, bc-devrev requested changes
I didn't mark every instance, but capitalization of titles and common nouns needs to be fixed throughout. Just because something is in the terminology list or is abbreviated doesn't mean it should be capitalized.

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/creating_a_keyring.mdx
> +# Creating Keyrings
Too short to be its own page. Combine it with another page, maybe "Getting Started".

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/adaas_overview.mdx
> +```mermaid
Fern does not support Mermaid diagrams. You can go to mermaid.live and export a PNG for inclusion.

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/adaas_overview.mdx
> +It is useful to know how the system works though, so this section explains how ADaaS works at a high level.
```suggestion
This section explains how ADaaS works at a high level.
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/adaas_overview.mdx
> +It’s also useful to know that Airdrop uses its own AWS S3 structure
```suggestion
Airdrop uses its own AWS S3 structure
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/adaas_overview.mdx
> +Airdrop-as-a-Service (ADaaS) as a system consists of the internal Airdrop components and a Worker (Extractor or Loader),
No cap on entities/objects, which are common nouns. https://www.notion.so/devrev/Should-a-product-or-feature-name-be-capitalized-20088da3e4074b18b0bec42555522c3a?pvs=4
```suggestion
Airdrop-as-a-Service (ADaaS) as a system consists of the internal Airdrop components and a worker (extractor or loader),
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/adaas_overview.mdx
> +For clarity, Artifact API and Airdrop are shown as separate entities,
I don't understand this paragraph.

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/extracting_attachments.mdx
> +# Attachment Extraction phase
Sentence case on titles. https://www.notion.so/devrev/Which-words-in-a-heading-or-title-should-be-capitalized-81984d54dd414af5b343bce1327c05bd?pvs=4
```suggestion
# Attachment extraction phase
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/extracting_attachments.mdx
> +the Extractor has to upload each Attachment to DevRev’s S3 using the using S3Interact.
Would be good to indicate what S3Interact is. If it is an API:
```suggestion
the Extractor has to upload each attachment to DevRev’s S3 using the `S3Interact` API. 
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/extracting_attachments.mdx
> +After uploading an attachment or a batch of attachments, the Extractor also has to prepare and upload an SSOR attachment file.
What is SSOR?

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/extracting_data.mdx
> +# Data Extraction Phase
Too short to be its own page. Combine it with another page, maybe "Extraction phases".

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/extracting_external_sync_units.mdx
> +# Extract External Sync Units Phase
Too short to be its own page. Combine it with another page, maybe "Extraction phases".

2024-07-09 20:55 UTC, bc-devrev commented on fern/versions/public.yml
> +              - page: "Obsevability"
```suggestion
              - page: "Observability"
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/terminology.mdx
> +# Terminology
I'd recommend against having a separate terminology page and just include these descriptions where the concepts are introduced. It's not a good user experience and introduces maintenance issues.

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/terminology.mdx
> +For Jira, this would be the organization name in the Jira domain name, i.e. `devrev` in `devrev.atlassian.net`.
```suggestion
For Jira, this would be the organization name in the Jira domain name, for example `devrev` in `devrev.atlassian.net`.
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/terminology.mdx
> +For GitHub, this would be the organization name, i.e. `devrev` in `github.com/devrev`.
```suggestion
For GitHub, this would be the organization name, for example `devrev` in `github.com/devrev`.
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/creating_a_keyring.mdx
> +Keyrings are a DevRev-specific mechanism for managing authentication for External Systems.
```suggestion
Keyrings are a DevRev-specific mechanism for managing authentication for external systems.
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/creating_a_keyring.mdx
> +They are called Connections in the DevRev app.
Ok to capitalize and bold here since it's literal text found in the UI.
```suggestion
They are called **Connections** in the DevRev app.
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/creating_a_keyring.mdx
> +They provide a secure way to store and manage credentials within your DevRev Snap-In.
```suggestion
They provide a secure way to store and manage credentials within your DevRev snap-In.
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/extracting_attachments.mdx
> +For the Attachment Extraction phase of the import process,
```suggestion
For the attachment extraction phase of the import process,
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/extracting_metadata.mdx
> +(e.g., DevRev Issues must have a priority, users must have a name etc.).
```suggestion
(for example, DevRev Issues must have a priority, users must have a name).
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/extraction_phases.mdx
> +An Initial Import consists of the following phases:
```suggestion
An initial import consists of the following phases:
```

2024-07-09 20:55 UTC, bc-devrev commented on fern/docs/pages/references/adaas/terminology.mdx
> +A Forward Sync is a sync from an [External System](#external-system) to DevRev.
```suggestion
A forward sync is a sync from an [external system](#external-system) to DevRev.
```

2024-07-10 08:13 UTC, samod commented on fern/versions/public.yml
> +          - section: ADaaS
Can we move it one level up? @shashankcube ?

2024-07-10 08:26 UTC, samod commented on fern/docs/pages/references/adaas/extraction_phases.mdx
> +```mermaid
Can Fern render SVGs?

2024-07-10 08:28 UTC, samod commented on fern/versions/public.yml
> +                path: ../docs/pages/references/adaas/extraction_phases.mdx
It is a typo.

2024-07-10 08:29 UTC, samod commented on fern/docs/pages/references/adaas/creating_a_keyring.mdx
> +They provide a secure way to store and manage credentials within your DevRev Snap-In.
Are snap-ins always lowercase? Since it is a sort of a brand name for DevRev?

2024-07-10 08:31 UTC, samod commented on fern/docs/pages/references/adaas/extracting_attachments.mdx
> +For the Attachment Extraction phase of the import process,
We had a lengthy discussion regarding capitalizing terms and well, the Airdrop team argues, that capitalizing names of processes, domain objects, ... and other domain entities would make the documentation more clear.

Can we cross-link everything with the Terminology section?

2024-07-10 08:33 UTC, erazemk commented on fern/versions/public.yml
> +                path: ../docs/pages/references/adaas/extraction_phases.mdx
Do we need the chapter numbers? If not I agree with dashes, but because we prefixed with chapter numbers I set it with underscores.

2024-07-10 08:37 UTC, samod commented on fern/docs/pages/references/adaas/adaas_overview.mdx
> +```mermaid
Can we use SVG on fern docs?

2024-07-10 11:00 UTC, samod commented on fern/versions/public.yml
> +          - section: ADaaS
I have moved it up one level.

2024-07-10 11:02 UTC, samod commented on fern/versions/public.yml
> +                path: ../docs/pages/references/adaas/extraction_phases.mdx
Fixed.

2024-07-10 11:02 UTC, samod commented on fern/versions/public.yml
> +                path: ../docs/pages/references/adaas/extraction_phases.mdx
It WAS a typo :).

2024-07-12 12:18 UTC, samod commented on fern/docs/pages/references/adaas/extracting_attachments.mdx
> +After uploading an attachment or a batch of attachments, the Extractor also has to prepare and upload an SSOR attachment file.
I have tried to simplify and clarify this section. SSOR (meaning Source System of Record) is a term we would like to avoid in the future.

2024-07-12 12:21 UTC, samod commented on fern/versions/public.yml
> +              - page: "Obsevability"
Not relevant anymore, since we have moved Observability to Getting Started.

2024-07-15 16:06 UTC, bc-devrev commented on fern/docs/pages/references/adaas/creating_a_keyring.mdx
> +They provide a secure way to store and manage credentials within your DevRev Snap-In.
Yes. It's not a brand name. https://www.notion.so/devrev/Should-a-product-or-feature-name-be-capitalized-20088da3e4074b18b0bec42555522c3a?pvs=4

2024-07-15 16:07 UTC, bc-devrev commented on fern/docs/pages/references/adaas/extraction_phases.mdx
> +```mermaid
I believe so.

2024-07-15 16:29 UTC, erazemk commented
Titles are added twice:
<img width="266" alt="image" src="https://github.com/user-attachments/assets/23704cdc-2cfb-4d34-9bac-afe868741643">

2024-07-18 13:35 UTC, samod commented on fern/docs/pages/references/adaas/creating_a_keyring.mdx
> +They provide a secure way to store and manage credentials within your DevRev Snap-In.
I have modified cases for snap-ins.

2024-07-18 13:35 UTC, samod commented on fern/docs/pages/references/adaas/extracting_attachments.mdx
> +For the Attachment Extraction phase of the import process,
I have removed the Terminology section.

2024-07-18 17:55 UTC, samod commented
Dear @bc-devrev , @erazemk , also @radovan-jorgic.

I have managed to come through all the suggestions and comments, and also updated and edited the metadata chapter. Could you please re-review?

2024-07-18 17:55 UTC, samod commented
And also, how can I generate a preview?

2024-07-18 18:02 UTC, radovan-jorgic commented on fern/docs/pages/adaas/delete-phases.mdx
> +Airdrop initiates the attachments delete phase when the Sync is deleted from DevRev.
Didn't know this. Attachments deletion starts when import is deleted (and not visible through the UI)?

2024-07-18 18:04 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-attachments.mdx
> +when transitioning to the Data Extraction phase.
after Data is extracted, transformed and loaded?

2024-07-18 18:07 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-attachments.mdx
> +If Attachment Extraction failed, the snap-in must respond to Airdrop with a message with eventType `EXTRACTION_ATTACHMENTS_ERROR`.
Just curious if there is agreement regarding usage of word "eventType". Should we use "human language"? Something like "with event of type `EVENT_TYPE``?

2024-07-18 18:11 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-data.mdx
> +If data extraction failed in any moment of extraction, the snap-in must respond to Airdrop with a message with eventType `EXTRACTION_DATA_ERROR`.
Not tested but I believe we save the latest successful state and retrieve it in next iteration if import failed and we retried it? If this is true, maybe we can write it down also - can be really helpful?

2024-07-18 18:15 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-external-sync-units.mdx
> +In the external sync unit extraction phase, the extractor is expected to get the list of projects, repositories, etc.
Maybe add organizations and workspaces too. These are also pretty common.

2024-07-18 18:16 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-external-sync-units.mdx
> +In the external sync unit extraction phase, the extractor is expected to get the list of projects, repositories, etc.
Oh, you mentioned it in sentence below. Nevermind

2024-07-18 18:16 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-external-sync-units.mdx
> +Airdrop initiates the external sync unit extraction phase by starting the worker with a message with eventType:
Can we mention that this event is sent when user adds connection through the UI and click Next button or something like that?

2024-07-18 18:17 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-external-sync-units.mdx
> +then the item count should be `-1`, to avoid blocking the import with long-running queries.
or `undefined`, that also works

2024-07-18 18:19 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-metadata.mdx
> +During the extract metadata phase, the ADaaS snap-in must provide an `external_domain_metadata.json` file on each sync run. This file provides a structured way of describing external system's domain
On each sync run? This is a bit confusing.

2024-07-18 18:20 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-metadata.mdx
> +During the extract metadata phase, the ADaaS snap-in must provide an `external_domain_metadata.json` file on each sync run.
We have this sentence written two times

2024-07-18 18:22 UTC, radovan-jorgic commented on fern/docs/pages/adaas/getting-started.mdx
> +8. Define the `Connection`.
Should we describe steps how this is done like in step 7?

2024-07-18 18:23 UTC, radovan-jorgic commented on fern/docs/pages/adaas/getting-started.mdx
> +9. Create an `Import.`
ditto

2024-07-18 18:24 UTC, radovan-jorgic commented on fern/docs/pages/adaas/getting-started.mdx
> +This eliminates the need to expose sensitive information like passwords
this also handles token expiration for example, which is very useful - not sure if we want to mention that here though

2024-07-18 18:24 UTC, radovan-jorgic commented on fern/docs/pages/adaas/getting-started.mdx
> +snap-ins are snap-ins, and they inherit observability methodology from snap-ins.
?

2024-07-18 18:25 UTC, radovan-jorgic commented on fern/docs/pages/adaas/overview.mdx
> +It enables developers to create external workers, extractors and loaders to bring data from various external systems.
```suggestion
It enables developers to create external workers (extractors and loaders) to bring data from various external systems.
```

2024-07-18 18:26 UTC, radovan-jorgic commented on fern/docs/pages/adaas/overview.mdx
> +An extractor is an function in an ADaaS-capable snap-in responsible for extracting data from an external system, such as Jira, Zendesk,
```suggestion
An extractor is an function in an ADaaS-capable Snap-in responsible for extracting data from an external system, such as Jira, Zendesk,
```

2024-07-18 18:28 UTC, radovan-jorgic requested changes
Added comments, please check

2024-07-18 19:20 UTC, samod commented on fern/docs/pages/adaas/delete-phases.mdx
> +Airdrop initiates the attachments delete phase when the Sync is deleted from DevRev.
FIxed.

2024-07-18 19:22 UTC, samod commented on fern/docs/pages/adaas/extracting-attachments.mdx
> +when transitioning to the Data Extraction phase.
Fixed, also fixed all capitalizations of terms.

2024-07-18 19:23 UTC, samod commented on fern/docs/pages/adaas/extracting-attachments.mdx
> +If Attachment Extraction failed, the snap-in must respond to Airdrop with a message with eventType `EXTRACTION_ATTACHMENTS_ERROR`.
Perfect.

2024-07-18 19:25 UTC, samod commented on fern/docs/pages/adaas/extracting-data.mdx
> +If data extraction failed in any moment of extraction, the snap-in must respond to Airdrop with a message with eventType `EXTRACTION_DATA_ERROR`.
I do not understand what you mean. Please, explain.

2024-07-18 19:27 UTC, samod commented on fern/docs/pages/adaas/extracting-metadata.mdx
> +During the extract metadata phase, the ADaaS snap-in must provide an `external_domain_metadata.json` file on each sync run. This file provides a structured way of describing external system's domain
yes.

2024-07-18 19:32 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-data.mdx
> +If data extraction failed in any moment of extraction, the snap-in must respond to Airdrop with a message with eventType `EXTRACTION_DATA_ERROR`.
If import fails, the latest state (before we emitted error) should be sent to snap-in in next iteration if retry (re-run) button is cliked on the UI. This is not mentioned anywhere.

2024-07-18 20:15 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-attachments.mdx
> +If Attachment Extraction failed, the snap-in must respond to Airdrop with a message with eventType `EXTRACTION_ATTACHMENTS_ERROR`.
I meant "event of type `EXTRACTION_ATTACHMENTS_DONE`" and not "event of type `EVENT_TYPE` `EXTRACTION_ATTACHMENTS_DONE`".

2024-07-18 20:17 UTC, radovan-jorgic commented on fern/docs/pages/adaas/extracting-attachments.mdx
> +If Attachment Extraction failed, the snap-in must respond to Airdrop with a message with eventType `EXTRACTION_ATTACHMENTS_ERROR`.
So replace all "event of type `EVENT_TYPE`" with just "event of type" now.

2024-07-21 19:13 UTC, bc-devrev requested changes
Only one significant structural issue, the "how to get started" section of metadata extraction. I didn't necessarily suggest changes for every item in a group that all have the same issue, just the first one.

2024-07-21 19:13 UTC, bc-devrev commented on fern/docs/pages/adaas/extracting-data.mdx
> +- null values: All fields without a value should either be omitted or set to null. For example, if an external system provides values such as "", -1 for missing values, those must be set to null.
Initial caps on list items.
```suggestion
- Null values: All fields without a value should either be omitted or set to null. For example, if an external system provides values such as "", -1 for missing values, those must be set to null.
```

2024-07-21 19:13 UTC, bc-devrev commented on fern/docs/pages/adaas/extracting-data.mdx
> +- timestamps: Full-precision timestamps should be formatted as RFC3999 (`1972-03-29T22:04:47+01:00`), and dates should be just "2020-12-31"
End list items of this length with a period.
```suggestion
- Timestamps: Full-precision timestamps should be formatted as RFC3999 (`1972-03-29T22:04:47+01:00`), and dates should be just `2020-12-31`.
```

2024-07-21 19:13 UTC, bc-devrev commented on fern/docs/pages/adaas/extracting-data.mdx
> +Each line of the file contains `id`, and the optional `created_date` and `modified_date` fields in the beginning of the record.
No comma here.
```suggestion
Each line of the file contains `id` and the optional `created_date` and `modified_date` fields in the beginning of the record.
```

2024-07-21 19:13 UTC, bc-devrev commented on fern/docs/pages/adaas/extracting-data.mdx
> +Extracted artifacts can be validated with the `chef-cli` using
```suggestion
Extracted artifacts can be validated with the `chef-cli` using the following command:
```

2024-07-21 19:13 UTC, bc-devrev commented on fern/docs/pages/adaas/extracting-attachments.mdx
> +when after the data is extracted, transformed and loaded to DevRev.
```suggestion
after the data is extracted, transformed, and loaded to DevRev.
```

2024-07-21 19:13 UTC, bc-devrev commented on fern/docs/pages/adaas/extracting-attachments.mdx
> +The snap-in must respond to Airdrop with a message with with event of type `EVENT_TYPE` `EXTRACTION_ATTACHMENTS_PROGRESS` together with an optional progress estimate and relevant Artifacts
```suggestion
The snap-in must respond to Airdrop with a message with with event of type `EXTRACTION_ATTACHMENTS_PROGRESS` together with an optional progress estimate and relevant artifacts
```

2024-07-21 19:13 UTC, bc-devrev commented on fern/docs/pages/adaas/extracting-attachments.mdx
> +In both cases, Airdrop starts the snap-in with a message with with event of type `EVENT_TYPE` `EXTRACTION_ATTACHMENTS_CONTINUE`.
```suggestion
In both cases, Airdrop starts the snap-in with a message with with event of type `EXTRACTION_ATTACHMENTS_CONTINUE`.
```

2024-07-21 19:13 UTC, bc-devrev commented on fern/docs/pages/adaas/extracting-attachments.mdx
> +Once the attachment extraction phase is done, the snap-in must respond to Airdrop with a message with with event of type `EVENT_TYPE` `EXTRACTION_ATTACHMENTS_DONE`.
```suggestion
Once the attachment extraction phase is done, the snap-in must respond to Airdrop with a message with with event of type `EXTRACTION_ATTACHMENTS_DONE`.
```

2024-07-21 19:13 UTC, bc-devrev commented on fern/docs/pages/adaas/extracting-attachments.mdx
> +If attachment extraction failed, the snap-in must respond to Airdrop with a message with with event of type `EVENT_TYPE` `EXTRACTION_ATTACHMENTS_ERROR`.
```suggestion
If attachment extraction fails, the snap-in must respond to Airdrop with a message with with event of type `EXTRACTION_ATTACHMENTS_ERROR`.
```

2024-07-21 19:13 UTC, bc-devrev commented on fern/docs/pages/adaas/delete-phases.mdx
> +It is started by sending the worker a message with with event of type `EVENT_TYPE`: `EXTRACTION_DATA_DELETE`.
One or the other; both is cluttering.
```suggestion
It is started by sending the worker a message with with event of type `EXTRACTION_DATA_DELETE`.
```

2024-07-21 19:13 UTC, bc-devrev commented on fern/versions/public.yml
> +          - page: "Getting Started"
Sentence case on titles. https://www.notion.so/devrev/Which-words-in-a-heading-or-title-should-be-capitalized-81984d54dd414af5b343bce1327c05bd?pvs=4
```suggestion
          - page: "Getting started"
```

2024-07-21 19:13 UTC, bc-devrev commented on fern/versions/public.yml
> +          - page: "Extracting External Sync Units"
Start the titles with the object, not the action. Also suggest changing the filenames to match.
```suggestion
          - page: "External sync unit extraction"
```

2024-07-22 17:16 UTC, samod commented on fern/docs/pages/adaas/overview.mdx
> +HubSpot, etc. It uses a standardized communication protocol for talking to Airdrop and a standardized
I have removed the latin abbrevations.

2024-07-22 17:28 UTC, samod commented on fern/versions/public.yml
> +          - page: "Extracting External Sync Units"
I have fixed all titles in the public.yml, as well as modified the filenames and slugs.

2024-07-22 18:04 UTC, samod commented on fern/docs/pages/adaas/overview.mdx
> +updated data from the external system, such as Jira, Zendesk, HubSpot, etc. to DevRev. An extractor function
ok.

2024-07-22 18:05 UTC, samod commented on fern/docs/pages/adaas/overview.mdx
> +for talking to [Airdrop](https://docs.devrev.ai/import#airdrop-features) and a standardized data structure for all the files
Indeed.

2024-07-22 18:13 UTC, samod commented on fern/docs/pages/adaas/extraction-phases.mdx
> +- external sync units extraction,
They are sequential, and have numbered them

2024-07-22 18:47 UTC, samod commented on fern/docs/pages/adaas/extracting-metadata.mdx
> +## How to get started
I have added an introductionary paragraph explaing the step-by-step approach and numbered the sections below.

2024-07-22 18:49 UTC, samod commented on fern/docs/pages/adaas/extracting-metadata.mdx
> +If the external system supports custom types, or custom variants of some base record type, and you want to airdrop those
Airdropping is a verb :)

2024-07-22 19:55 UTC, bc-devrev approved these changes

2024-07-23 07:56 UTC, erazemk commented on fern/docs/pages/adaas/overview.mdx
> +load data from external systems and, export data back to external systems, and keep data in sync between DevRev and the external systems.
Very weird sentence.

2024-07-23 07:58 UTC, erazemk commented on fern/docs/pages/adaas/overview.mdx
> +of ADaaS snap-in to bring the data to DevRev or load the data to the external system.
```suggestion
Airdrop functions are executed in the context of _sync runs_, which is a directed operation that spans over many invocations
of an ADaaS snap-in to bring the data to DevRev or load the data to the external system.
```

2024-07-23 08:00 UTC, erazemk commented on fern/docs/pages/adaas/getting-started.mdx
> +   - [golang](https://go.dev/doc/install)
What is Go needed for?

2024-07-23 08:01 UTC, erazemk commented on fern/docs/pages/adaas/getting-started.mdx
> +4. Copy `Makefile.variable.example` to `Makefile.variable` and fill in the required variables.
This is not really a problem with the documentation, but I still don't understand why we can't use the standard `.env` and `.env.example`, everybody knows and uses those but us.

2024-07-23 08:03 UTC, erazemk commented on fern/docs/pages/adaas/extraction-phases.mdx
> +Airdrop extractions are done in _sync runs_. A sync run is one execution of an import or sync. If you do an inital import from
```suggestion
Airdrop extractions are done in _sync runs_. A sync run is one execution of an import or sync. If you do an initial import from
```

2024-07-23 08:03 UTC, erazemk commented on fern/docs/pages/adaas/extraction-phases.mdx
> +external system, that would be another sync run.
```suggestion
the external system, that would be another sync run.
```

2024-07-23 11:00 UTC, erazemk commented on fern/docs/pages/adaas/data-attachments-deletion.mdx
> +It is started by sending the span-in a message with event of type `EXTRACTION_ATTACHMENTS_DELETE`.
```suggestion
Airdrop initiates the attachments deletion phase when an import is deleted from the DevRev app, after the data deletion has completed.
It is started by sending the snap-in a message with an event of type `EXTRACTION_ATTACHMENTS_DELETE`.
```

2024-07-23 11:00 UTC, erazemk commented on fern/docs/pages/adaas/data-attachments-deletion.mdx
> +or `EXTRACTION_ATTACHMENTS_DELETE_ERROR` in case of an error.
```suggestion
The snap-in must respond to Airdrop with a message with an event of type `EXTRACTION_ATTACHMENTS_DELETE_DONE` when done,
or `EXTRACTION_ATTACHMENTS_DELETE_ERROR` in case of an error.
```

2024-07-23 11:11 UTC, samod commented on fern/docs/pages/adaas/data-extraction.mdx
> +Extracted artifacts can be validated with the `chef-cli` using the following command:
Will be soon. No link is available at this moment :)

2024-07-23 11:12 UTC, samod commented on fern/docs/pages/adaas/external-sync-units-extraction.mdx
> +that it can extract with the provided credentials and send it to Airdrop in its response.
Thx. I am keeping "it" since it is a list we are sending.

2024-07-24 08:16 UTC, radovan-jorgic approved these changes

2024-07-24 10:44 UTC, samod commented on fern/docs/pages/adaas/data-attachments-deletion.mdx
> +In the most common extraction use cases, there is nothing to do and snap-ins may reply with the completion message.
Fixed.

2024-07-24 13:58 UTC, merged