ISS-120468: Update documentation for the marketplace related commands
devrev/fern-api-docs pull request #95
Opened 2024-09-25 13:22 UTC by MhcVintar

Added documentation regarding marketplace listings.

https://app.devrev.ai/devrev/works/ISS-120468

2024-09-25 16:42 UTC, bc-devrev requested changes

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +  - [Marketplace listing](#marketplace-listing)
Titles should be in sentence case. https://www.notion.so/devrev/Which-words-in-a-heading-or-title-should-be-capitalized-81984d54dd414af5b343bce1327c05bd?pvs=4

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +## Table of Contents
Not necessary as Fern automatically generates a TOC from the headings.

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +This object is utilized for submission purposes when the marketplace publisher is either creating a new listing for the
This definition doesn't say what it is, only restates its name.

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +A marketplace serves as a platform for creators and consumers to collaborate, engage, and conduct transactions. It
Don't restate the term as the subject of a sentence.
```suggestion
A platform for creators and consumers to collaborate, engage, and conduct transactions. It
```

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +Marketplace listing refers to all the marketplace items that belong to the same marketplace and have the same slug. It
```suggestion
All the marketplace items that belong to the same marketplace and have the same slug. It
```

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +The publishing process begins by initiating a marketplace submission, which entails requesting the creation of a new
Rewrite in active voice.

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +## Get Started
Would be better to have the following sections as a procedure of numbered steps where each step is an imperative. https://www.notion.so/devrev/How-should-instructions-be-written-dac658b248d94db6a0c301079cffbbf5?pvs=4

You can have an item labeled "Before you begin" that includes installing the CLI and creating a snap-in with links.

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +Snap-Ins, [follow this guide here](https://github.com/devrev/snap-in-docs/blob/main/start.md), to create your first
No cap on "snap-in".
```suggestion
snap-ins, [follow this guide here](https://github.com/devrev/snap-in-docs/blob/main/start.md), to create your first
```

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +properties (e.g. name, description, icon, etc.).
Either list all the required properties or don't mention them.

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +## Auto-upgradation of marketplace-items
"Upgradation" is not a word.
```suggestion
## Automatic upgrade of marketplace items
```

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +## Some helpful commands
```suggestion
## Command reference
```

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +To create a new marketplace listing, run the following command, which will start a __wizard__ to guide you through the
What do the double underscores around "wizard" indicate?

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +- When creating an initial submission, property __access level__ should be set to `restricted`.
Numbered list since it's a sequence of steps.
```suggestion
1. When creating an initial submission, property __access level__ should be set to `restricted`.
```

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +```bash
Indent codeblock under the parent item.
```suggestion
  ```bash
```

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +Once an organization is invited to a marketplace listing, their members can *view* and *install* it within their own
No need to emphasize.
```suggestion
Once an organization is invited to a marketplace listing, their members can view and install it within their own
```

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +When a marketplace listing is shared with an organization, this information is **retained when creating new submissions
No need for emphasis.
```suggestion
When a marketplace listing is shared with an organization, this information is retained when creating new submissions
```

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +is utilized. To update the `meta_score`, one needs to provide the `marketplace item ID` along with the desired score (
```suggestion
is utilized. To update the `meta_score`, provide the `marketplace item ID` along with the desired score (
```

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +within the allowed range of values: [1, 100000]):
```suggestion
within the allowed range of values 1 to 100,000:
```

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +Please note that API usage is restricted exclusively to `DEV-0` users.
Remove the ranking section from public documentation if it's only available to DevRev.

2024-09-25 16:42 UTC, bc-devrev commented on fern/docs/pages/references/marketplace-listings.mdx
> +List marketplaces:
Remove if as @kosenina says there is only one marketplace.

2024-09-25 16:43 UTC, bc-devrev commented
Also address comments from EkLine.

2024-09-26 07:21 UTC, MhcVintar commented on fern/docs/pages/references/marketplace-listings.mdx
> +List marketplaces:
Yes that is correct. There should only be the 'universal' marketplace

2024-09-30 06:15 UTC, kosenina commented on fern/docs/pages/marketplace-listings.mdx
> +    To create a new marketplace listing, run the following command, which will start a wizard to guide you through the process:
Do you think we should add some GIF to show how wizard for creating a new initial submission looks like?

2024-09-30 06:16 UTC, kosenina commented on fern/docs/pages/marketplace-listings.mdx
> +    devrev marketplace_submissions create
Same here, the command is the same as the one for creating an initial submission, but the wizard is not. We can add some GIF to demonstrate creating new submissions for an existing item.

2024-09-30 06:17 UTC, kosenina commented on fern/docs/pages/marketplace-listings.mdx
> +    Submissions whose state is `in review` cannot be modified.
or `approved`.

2024-09-30 06:23 UTC, kosenina commented on fern/docs/pages/marketplace-listings.mdx
> +## Automatic upgrade of marketplace listings
We should mention automatic upgrade refers to marketplace listing installations.

2024-09-30 06:25 UTC, kosenina commented on fern/docs/pages/marketplace-listings.mdx
> +When a listing is marked as restricted, it is possible to change the access level to `public`. However, the reverse process, changing the access level from `public` to `restricted`, is not permitted.
Make this a "callout".

2024-09-30 12:03 UTC, kosenina approved these changes

2024-09-30 17:18 UTC, bc-devrev approved these changes
Two main things to fix before merging:
- Put states in italics, not code phrase.
- Don't use "we"; use "you" instead.

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +#### Marketplace listing
H3 to match the preceding items.
```suggestion
### Marketplace listing
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +The marketplace publisher creates a marketplace submission, requesting the creation of a new marketplace listing or updating an existing one. Once the submission is ready for review, the publisher tr
States in italics.
```suggestion
The marketplace publisher creates a marketplace submission, requesting the creation of a new marketplace listing or updating an existing one. Once the submission is ready for review, the publisher transitions it to the _Waiting for review_ state. During this phase, an admin reviews and decides whether to approve or reject the submission. If the admin approves the submission, the publisher can proceed to publish it. However, if the admin rejects the submission, the publisher can update and resubmit it for another round of review.
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +    When creating a new marketplace listing, an initial marketplace submission must be created with all the mandatory properties.
Move to follow the "Initial submission" heading.

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +## Get started
"Get started" is too vague.
```suggestion
## Manage marketplace listings
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +    When a marketplace listing already exists (there is at least one marketplace item in the `published` or `end of sale` state), we can modify it by creating a new marketplace submission. We can mod
```suggestion
    When a marketplace listing already exists (there is at least one marketplace item in the _Published_ or _End of sale_ state), you can modify it by creating a new marketplace submission.
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +    The newly created marketplace submission is in the `draft` state. In order to publish it, we first have to transition it to `waiting for review` state. This can be done by running the following c
```suggestion
    The newly created marketplace submission is in the _Draft_ state. In order to publish it, we first have to transition it to _Waiting for review_ state. This can be done by running the following command, which will start a wizard to guide you through the process:
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +    Once the submission is transitioned to the `waiting for review` state, it needs to be approved by a marketplace admin. While in review, the state of the submission is `in review`. Once it is revi
```suggestion
    Once the submission is transitioned to the _Waiting for review_ state, it needs to be approved by a marketplace admin. While in review, the state of the submission is _In review. Once it is reviewed, the state will be changed to either _Approved_ or _Rejected_.
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +    If the submission was rejected, we can transition it back to `draft` state and modify it to satisfy the requirements. Once it is updated, we can transition it back to `waiting for review` state t
```suggestion
    If the submission was rejected, you can transition it back to _Draft_ and modify it to satisfy the requirements. Once it is updated, you can transition it back to _Waiting for review_ to be reviewed again.
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +    If the submission was approved, we can publish it using the following command, which will start a wizard to guide you through the process:
```suggestion
    If the submission was approved, you can publish it using the following command, which will start a wizard to guide you through the process:
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +    To make sure that marketplace item was published we can retrieve it using its ID:
```suggestion
    To make sure that marketplace item was published you can retrieve it using its ID:
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +    If a marketplace submission was created by mistake or is no longer relevant, it can be deleted. However, deletion of a submission is only permitted for the owners of the submission and is restric
```suggestion
    If a marketplace submission was created by mistake or is no longer relevant, it can be deleted. However, deletion of a submission is only permitted for the owners of the submission and is restricted to submissions that are in the _Draft_ or _Rejected_ state.
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +By default, all marketplace listings are accessible to all users. However, if someone wants to share a specific listing with certain organizations only, they should follow the steps below:
```suggestion
By default, all marketplace listings are accessible to all users. However, if you want to share a specific listing with certain organizations only, follow the steps below:
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +1. When creating an initial submission, property __access level__ should be set to `restricted`.
This is what I see in metadatal.yaml. Variable names should be in code phrase.
```suggestion
1. When creating an initial submission, property `access_level` should be set to `restricted`.
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +4. To invite a specific DEV organization to the newly created item, execute the following command:
```suggestion
4. To invite a specific dev organization to the newly created item, execute the following command:
```

2024-09-30 17:18 UTC, bc-devrev commented on fern/docs/pages/marketplace-listings.mdx
> +Once an organization is invited to a listing, their members can view and install it within their own organization.
```suggestion
Once an organization is invited to a listing, its members can view and install it within their own organization.
```

2024-10-01 08:33 UTC, merged