docs: add custom objects beta API documentation
devrev/fern-api-docs pull request #96
Opened 2024-10-01 06:32 UTC by shivansh

https://app.devrev.ai/devrev/works/ISS-121317

The PR will be ready for review as soon as the custom object APIs are beta (in-progress) ✅

2024-10-01 06:43 UTC, shivansh commented on fern/docs/pages/custom-objects.mdx
> +For more details, please refer to the [Customization](./customization.mdx) documentation.
@Atul-Butola please let me know if this isn't the right way to link other docs.

2024-10-01 07:20 UTC, shivansh commented on fern/docs/pages/custom-objects.mdx
> +For more details, please refer to the [Customization](./customization.mdx) documentation.
I tested this on the published docs preview and it doesn't work.

2024-10-01 08:23 UTC, shivansh commented on fern/docs/pages/custom-objects.mdx
> +For more details, please refer to the [Customization](./customization.mdx) documentation.
Fixed this.

2024-10-03 06:57 UTC, praneethratna commented on fern/docs/pages/custom-objects.mdx
> +    "id_prefix": "CAMP"
Can we add definitions regarding `is_custom_leaf_type` and `id_prefix`?

2024-10-03 07:04 UTC, praneethratna approved these changes

2024-10-03 19:41 UTC, bc-devrev requested changes

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +* [Introduction](#custom-objects)
Remove. Fern automatically constructs a TOC from the headings so no need to create one explicitly.

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +## Introduction
Remove.
```suggestion
```

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +## Quick start
```suggestion
## Custom object example
```

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +## Key concepts
Move this up to be the first section after the intro lines.

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +1. **Leaf Type**: The base type of your custom object (e.g., "campaign"). Note that for custom objects, `is_custom_leaf_type` must be set to `true` to differentiate it from standard DevRev objects.
```suggestion
1. **Leaf type**: The base type of your custom object (for example, "campaign"). For custom objects, `is_custom_leaf_type` must be set to `true` to differentiate it from standard DevRev objects.
```

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +2. **Subtype**: A more specific categorization within a leaf type (e.g., "promotion" or "advertising" for a "campaign" leaf type).
```suggestion
2. **Subtype**: A more specific categorization within a leaf type (for example, "promotion" or "advertising" for a "campaign" leaf type).
```

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +3. **Custom Fields**: User-defined fields that store specific data for your custom object.
```suggestion
3. **Custom fields**: User-defined fields that store specific data for your custom object.
```

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +4. **Unique Key**: The `unique_key` is a unique identifier for each custom object. This is useful for maintaining idempotency when retrying custom object creation requests.
```suggestion
4. **Unique key**: A unique identifier for each custom object. This is useful for maintaining idempotency when retrying custom object creation requests.
```

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +5. **ID Prefix**: The `id_prefix` should be unique and is used to generate the display ID for the custom object. In the above example, the `id_prefix` is "CAMP" and the generated custom object displa
```suggestion
5. **ID prefix**: Used to generate the display ID for the custom object. In the above example, the `id_prefix` is "CAMP" and the generated custom object display ID is "C-CAMP-1". The display ID is used to identify the custom object in the UI, similar to the standard DevRev object display IDs like "ISS-001" for issues.
```

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +## Custom object lifecycle
Move the contents of this section up to the lifecycle operations reference.

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +### Create a schema and a custom object
Insert an H2 here
```suggestion
## Custom object lifecycle

### Create a schema and a custom object
```

2024-10-03 19:41 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +## Extended use cases
Is there another description you could use besides "extended"?

2024-10-09 05:51 UTC, shivansh commented on fern/docs/pages/custom-objects.mdx
> +## Quick start
How about "Getting started"? "Custom object example" doesn't fit well with the flow of the doc.

2024-10-09 06:03 UTC, shivansh commented on fern/docs/pages/custom-objects.mdx
> +## Extended use cases
How about "Beyond basic use cases".
Some other alternatives:
1. Advanced Scenarios
1. Advanced Applications
1. Complex Use Cases
1. Advanced Implementations
1. Specialized Configurations
1. Advanced Features
1. Power User Techniques
1. Advanced Customization
1. Beyond Basic Usage
1. Advanced Functionality

2024-10-09 18:14 UTC, bc-devrev commented on fern/docs/pages/custom-objects.mdx
> +## Extended use cases
Extended, advanced, and beyond basic all have the same meaning, which is nothing. So if there isn't a term that's meaningful I guess you can leave it as-is.

2024-10-11 15:37 UTC, bc-devrev approved these changes

2024-10-14 10:24 UTC, merged